### ISSUE TITLE
Editing ACF fields then Publish ignores changes

### ISSUE THREAD

**Issue by jamiechong** [jamiechong/revisionize#1]
1. Revisionize
2. Edit ACF Fields
3. Click _Publish_

Result: The revision is published, but the ACF fields aren't. 
Reason: `transition_post_status` hook fires too early. The revision `$post` content has been saved, but its `meta fields` have not (they're saved shortly after). So the `meta fields` of the revision aren't updated when we `copy_post` over top of the original. 
Fix: Need to hook into an action later on. Possibly [publish_post](https://codex.wordpress.org/Plugin_API/Action_Reference/publish_post).

**Work Around**
1. Revisionize
2. Edit ACF Fields
3. Click _Save Draft_
4. Click _Publish_

**Comment by brucesdad13** [comment]
Excellent!

**Comment by thegaffney** [comment]
I fixed this (for ACF at least) by changing the hook to `acf/save_post`  and I had to change the on_publish_post function to 
`
function on_publish_post($post_id) {
	$post = get_post($post_id);
	$new_status = get_post_status($post_id);
  	if($post && $new_status == 'publish') {
		$id = get_revision_of($post);
		if ($id) {
		  $original = get_post($id);
		  if ($original) {
			publish($post, $original);
		  }
        }
  }
}
`

**Comment by jamiechong** [comment]
@thegaffney Will this change continue to work without ACF? If so, care to create a PR? Thanks for looking into a workable solution!

**Comment by thegaffney** [comment]
I'd imagine no, but I think you could just do a simple check like this to see if ACF is installed

```
if (has_action( 'acf/save_post' ) ) {
     add_action('acf/save_post', __NAMESPACE__.'\\on_publish_post', 130, 1);
} else {
     add_action('transition_post_status', __NAMESPACE__.'\\on_publish_post', 10, 3);
}
```
That change still works with ACF, but I won't be able to test it on a site without it, but it seems like it would be the correct way to do it.

**Comment by jamiechong** [comment]
Thanks for the help @thegaffney. I had to modify your changes a bit to make it work with scheduled posts. Will get this up onto WP.org.

**Comment by thegaffney** [comment]
Yeah no problem! Glad I could help, thanks for making it in the first place


________________________________
