### ISSUE TITLE
Fatal error on multisite installation

### ISSUE THREAD

**Issue by mlangone** [jamiechong/revisionize#19]
Warning: require_once(/home/langone/public_html/wp-content/plugins/revisionize/settings.php): failed to open stream: No such file or directory in /home/langone/public_html/wp-content/plugins/revisionize/revisionize.php on line 34

Fatal error: require_once(): Failed opening required '/home/langone/public_html/wp-content/plugins/revisionize/settings.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/langone/public_html/wp-content/plugins/revisionize/revisionize.php on line 34

Steps to reproduce on my end. 
1. Delete plugin - had to get site back
2. Install 1.3.6 - network activate
3. Update to 2.0 through wp-admin
4. Network Activate 2.0
5. Errors, see Screenshots

I have deactivated all other plugins, and retried these steps to the same error. This is on a go-daddy dedicated server. Let me know if I can help in any way, if you would like a temp login to reproduce the issue. I use this site to test things so there will be no issues if you need to use it to troubleshoot.

![screen shot 2018-03-04 at 8 17 03 am](https://user-images.githubusercontent.com/4027703/36947246-960684f4-1f86-11e8-98be-647167030c45.png)
![screen shot 2018-03-04 at 8 30 59 am](https://user-images.githubusercontent.com/4027703/36947250-99a33efe-1f86-11e8-8bad-959fea943cfb.png)
![screen shot 2018-03-04 at 8 32 13 am](https://user-images.githubusercontent.com/4027703/36947252-9ba71932-1f86-11e8-9bfe-4d3edc9979f2.png)

**Comment by jamiechong** [comment]
Hey thanks for reporting this! I didn't test by installing via wordpress.org. Argh. I had forgot to `svn add` two files (problem with working with to code repositories). 

version 2.0.1 should fix the fatal error. You can go to Dashboard -> Updates and click the "Check Again" button to get your install to discover the available update again (it only checks very 12 hours). 

This leads to another likely problem... I haven't tested on multisite installs. I think the settings panel is going to be on a per site basis, which is probably what we don't want. We want the settings and the addons to be network wide. 

I will figure that out and get another release out that supports multisite later tonight. Will keep you posted.

**Comment by jamiechong** [comment]
It'd actually be good to hear from you on how you use Revisionize in a network environment. 

- Does each Site Admin activate Revisionize on a case by case basis? Or do you network activate it? 
- Should the Revisionize settings/configuration apply network wide? Or on a site-by-site basis? 
- Check out https://revisionize.pro - these are the paid addons. When you install these, should they applied Network wide or on a site-by-site basis? 

I clearly haven't used multisite much...

Looking forward to your suggestions.

**Comment by mlangone** [comment]
We use it network activated, each of our subsite owners are part of a
franchise and have a custom role set that allows for revisionize specific
pages, so in our application we would not need settings per site. We would
be setting as a global.

I think for best usability to cover a range of different users having a per
site settings would be best.

I'm interested in the paid options and would be interested in seeing if we
could extend the functionality to a custom user roll instead of just a
subscriber. Also do we have the ability to hook into the text output to
change revisionize to "revise post/page" for buttons

Most multisite installations allow for different websites so be settings
per site it's probably the way I would stick with.

**Comment by jamiechong** [comment]
This is more involved than I thought. I think the settings should be settable on a site-by-site basis. The addons should be Network settings so that super admin installs an addon and it's available for all the sites. 

The custom user role should work, I'm looking at capabilities, not roles. Things like: 
`current_user_can('edit_posts')`
`current_user_can('publish_post', $post->ID)`
`current_user_can('edit_post', $post->ID)`
So it should work for other roles your create. 

To change the text, try adding a filter: `revisionize_create_revision_button_text`. This would affect the 'Revisionize' link from the post list as well as the button on the post edit page. 

Once I have multisite settings working, I'll send you a link with a build you can try out. Give me a few days though!

**Comment by mlangone** [comment]
No problem anything I can do to help let me know.

**Comment by mlangone** [comment]
New version updates fixes the original issue closing it out.

**Comment by jamiechong** [comment]
Hi @mlangone can you give me an update on version 2.1.0? You've been using it this last week without issue? I'm going to deploy it to wordpress org today.

**Comment by mlangone** [comment]
This will work for most users, we however need to globally update so that
all sub sites have the same options set.

mL
