### ISSUE TITLE
Make plugin root adjustable via filter

### ISSUE THREAD

**Issue by piscis** [jamiechong/revisionize#21]
Would it be possible to have a filter where we can set an alternative plugin root for the revision addons. The problem we currently having is that our plugins are not versioned but get installed from a composer repository. After every deploy the plugins get scrapped and reinstalled. Having the addons folder inside of the plugin folder would lead to changes in our deployment process where we have to copy over the files every time.

Just want to know what your view on the topic is before I provide a pull request.

**Comment by jamiechong** [comment]
Not a bad idea. I'll implement something and get it deployed with my 2.1.0 release.

**Comment by jamiechong** [comment]
Example: 
```
add_filter('revisionize_addons_root', function($path) {
  $uploads = wp_upload_dir();
  return $uploads['basedir'].'/revisionize/addons';
});
```
