### ISSUE TITLE
Error when publishing a revision with post status 'pending'

### ISSUE THREAD

**Issue by kshaner** [jamiechong/revisionize#29]
We have our instance of revisionize setup to allow contributors to submit revisions a particular post.  We setup a new capability called create_revisions that we're assigning to most roles and filtered `revisionize_user_can_revisionize`.

However, when someone with `publish_posts` publishes the post, an error occurs because the call to `get_latest_wp_revision` returns null because `wp_get_post_revisions` assumes the 'revision' status and not `pending`.  Then it is used directly in `is_wp_revision_different` assuming it's an object.  It creates a waterfall of errors including not deleting the revision.

![image](https://user-images.githubusercontent.com/1686106/39539188-d9c42976-4df3-11e8-90e4-d6aff22d132d.png

The errors subside after modifying line 236 to the following:

```php
    if ( is_object($revision_before) && is_object($revision_after) && is_wp_revision_different($revision_before, $revision_after)) {
```

I know we may be using it a bit custom, but this check would help with many use cases I believe for advanced publishing flows.

**Comment by jamiechong** [comment]
Hi @kshaner 

Seems like this function fails if both $a and $b are null. The `is_wp_revision_different` function should probably look like this: 
`return $a && !$b || !$a && $b || $a && $b && $a->ID != $b->ID;`

I'll deploy this fix soon. 

Have you checked this out? https://revisionize.pro/downloads/contributors-can/

**Comment by kshaner** [comment]
Thanks Jamie, I did check this out, but our custom work pre-dated what you released.  We'll look into seeing if it matches what we have setup already.
