### ISSUE TITLE
Unique class on the revisionize button

### ISSUE THREAD

**Issue by massimpressions** [jamiechong/revisionize#40]
In the post edit screen, the revisonise button simply has a class of 'button'. It would be good to have a unique class for revisionise also on the button to ease styling. Happy to submit a PR if this would help.

**Comment by jamiechong** [comment]
The `button` class is a Wordpress class to give the default button styling. I suppose we could add a second class like `revisionize-create-revision-button`. PR is welcome.

**Comment by massimpressions** [comment]
Great - I'll submit later from.
